name: sextionary
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  firebase_auth: ^5.1.1
  firebase_core: ^3.1.1
  provider: ^6.1.2
  date_time_picker: ^2.0.0
  cloud_firestore: ^5.0.1
  firebase_storage: ^12.1.1
  flutter_rating_bar: ^4.0.0
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logos/logo_main.png

  